### ISSUE TITLE
Migrate the GYB template to Sourcery

### ISSUE THREAD

**Issue by uraimo** [uraimo/Bitter#5]
Currently, a GYB template is used to generate specific extensions for each integer type.
Even if it's quite easy to figure out how GYB templating works, migrating the template to Sourcery will make the template seem a little less esoteric.
The bash script that generates the classes will have to be updated too.

**Comment by darthpelo** [comment]
I will work also on this one, because after the Krzysztof's talk at the last #Pragma conference, I want to start to use in my company too :D

**Comment by uraimo** [comment]
Thanks!!! 👍👍
