### ISSUE TITLE
Add a method to generate masks

### ISSUE THREAD

**Issue by uraimo** [uraimo/Bitter#6]
A small method that generates bit mask for a given number of bits could be useful sometimes.
It could look something like `mask(bits:msb:)`, where bits would be the number of bits that need to be set to `1` and msb a boolean(no need for an enum here) that select if those bits need to be set from the MSB(right) or LSB(left).

Note: Since .allZeroes has been deprecated in Swift 4, when this method is available .allOnes should be removed, it makes no sense to keep it around when mask() can do the same thing and its sibling it's not around anymore.

**Comment by darthpelo** [comment]
@uraimo I will try, so I can also learn something more (GYB) 🙂

**Comment by darthpelo** [comment]
Just opened a WIP pull request #7 :)

**Comment by uraimo** [comment]
Fixed!
