### ISSUE TITLE
Error in "Specific Byte subscript" example

### ISSUE THREAD

**Issue by chrisbartley** [uraimo/Bitter#9]
The last line of the first example of the [Specific Byte subscript](https://github.com/uraimo/Bitter#specific-byte-subscript) section reads:

```
// Let's change the third byte
i[3] = 0xAA   //Error! There is no 3rd byte!
```

However, there's no actual error here because there _is_ a 3rd byte.  I was following along in code and at first didn't catch that there's no error, so I thought maybe that Bitter was just silently ignoring the out-of-bounds index since nothing appeared to change. But of course nothing would change by setting byte 3 to 0xAA since it's already 0xAA.

Anyway, I'd suggest something like this instead:

```
// Let's change the fourth byte
i[4] = 0xFF   //Error! There is no 4th byte!
```

**Comment by uraimo** [comment]
Hi, you are 100% correct, thanks for taking the time to open this issue and for using this library!

**Comment by chrisbartley** [comment]
Thanks for the super fast fix!  Also, sorry to be That Guy, but the comment above the line needs fixing to "Let's change the fourth byte" 😬

**Comment by uraimo** [comment]
Oops 😅
